services:
  web:
    image: node:alpine
    networks:
      - frontend

  api:
    image: node:alpine
    command: sleep 3600
    networks:
      - frontend
      - backend

  db:
    image: postgres:alpine
    environment:
      POSTGRES_PASSWORD: example
    networks:
      - backend

networks:
  frontend:
  backend:
